### ISSUE TITLE
Running issues

### ISSUE THREAD

**Issue by dyabel** [vimalabs/VIMABench#1]
File "/data_4T/dy/git-repos/VimaBench/vima_bench/tasks/components/encyclopedia/textures.py", line 15, in _texture_fpath
    with importlib_resources.files("vima_bench.tasks.assets.textures") as p:
AttributeError: __enter__
Hi, thank you for your greak work! When I run the example code, I get this error. Can you help me figure out? Thanks.

**Comment by yunfanjiang** [comment]
Hey, thank you for pointing out this error! We have fixed it. Feel free to let us know if you encounter further issues.
