### ISSUE TITLE
Tips to add some personalized objects?

### ISSUE THREAD

**Issue by SiyuanHuang95** [vimalabs/VIMABench#15]
Hi, 

thanks for the sharing of your great work.

I am currently using VIMABench to collect some dataset for the training purpose. And I would like to extend current setup for more diverse objects. Could you provide some info w.r.t the object creation and insertion?

**Comment by yunfanjiang** [comment]
To add new objects, you can follow the definition [here](https://github.com/vimalabs/VIMABench/blob/main/vima_bench/tasks/components/encyclopedia/objects.py) and add new entry to `ObjPedia`. You also need to place urdf assets into this [folder](https://github.com/vimalabs/VIMABench/tree/main/vima_bench/tasks/assets). After these steps you should be able to instantiate your custom objects. Let me know if you have further questions.
