### ISSUE TITLE
L4 tasks heldout?

### ISSUE THREAD

**Issue by SiyuanHuang95** [vimalabs/VIMABench#16]
Hi,

I noticed that the L4 task file is currently empty, as shown in [file](https://github.com/vimalabs/VIMABench/blob/main/vima_bench/tasks/partition_files/novel_task_generalization.yaml). Is it currently heldout for some challenge test? And how can we gain access to it?

**Comment by yunfanjiang** [comment]
The configuration is not empty. We left empty arguments for each task to use default values. You can access them through the standard `vima_bench.make` API.
