### ISSUE TITLE
How to run paper evaluation

### ISSUE THREAD

**Issue by mees** [vimalabs/VIMABench#2]
Hi there,
awesome work! could you please provide a command on how to run the benchmark? For example, how can I reproduce the paper results for the 4 level evaluation protocol with the provided checkpoints? Thanks for the help in advance!

**Comment by yunfanjiang** [comment]
Hey, thank you for your interest! Please refer to this [repo](https://github.com/vimalabs/VIMA) for algorithmic details. We will add further instructions soon. Stay tuned.
