### ISSUE TITLE
A simple API for query

### ISSUE THREAD

**Issue by quantumiracle** [vimalabs/VIMABench#4]
Hi, 

Thanks a lot for the great work!
However, I'm wondering if it's possible to provide a simple script with API to query the pre-trained VIMA model with any user specified prompt, given a chosen task. 

Best

**Comment by yunfanjiang** [comment]
Hey, thank you for your interest in our work. This is a brilliant idea and we will investigate if additional bandwidth is available. Meanwhile, feel free to check the [algorithm repo](https://github.com/vimalabs/VIMA) for demo scripts.
