### ISSUE TITLE
Camera parameter setting

### ISSUE THREAD

**Issue by XihangYU630** [vimalabs/VIMABench#6]
1) I notice that x/z axis position of front and top cameras are very large (1000 + 0.5 - front_offset, 0, 1000) and (0.5, 0, 1000.0).  Why do you set the parameters like this? 

2) A similar question for Field of View, how do you set that?

3) If I change the parameters there will be no images in view. What is the issue? Can we change the position of camera and the near/far plane distance (zrange) of camera without losing views?

**Comment by XihangYU630** [comment]
Can we change the position of camera and the near/far plane of camera without losing views?

**Comment by DeeDive** [comment]
Hi@XihangYU630, thanks for your interest in our work! The setting of the distant cameras is to produce near-perfect imaging to mitigate the lack of consideration on the affordance prediction in the vision module which is a commonly-existing issue as the pin-hole camera will also capture the sides of the objects (You can try to put cameras within closer range, say (10 meters in height) . It may also work.). Regarding your second and third questions, yes, you can feel free to change the configurations of the virtual camera without losing views. It is based on the rendering of computer graphics. Some tutorials in the rendering of OpenGL may help! For example, you may refer to http://info.ee.surrey.ac.uk/Teaching/Courses/CGI/lectures_pdf/opengl3.pdf

Feel free to ask if you have more questions!

**Comment by yunfanjiang** [comment]
Thanks @DeeDive for the answer. Closing this issue now. Feel free to re-open upon further questions.
